/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.collectiveidea.twirp

import kotlin.test.Test
import kotlin.test.assertTrue

class GeneratorTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Generator()
        assertTrue(true) // TODO: Flesh out
    }
}
