name: Lint - Kotlin

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install ktlint 1.3.1
        # https://pinterest.github.io/ktlint/1.3.1/install/cli/#download-using-curl
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.3.1/ktlint
          chmod a+x ktlint
          mv ktlint /usr/local/bin/

      - name: ktlint version
        run: ktlint --version

      - name: ktlint
        run: ktlint
